version: "3.3"

services:

  blog:
    build: .
    image: blog
    volumes:
      - .:/app
    container_name: blog
    ports:
      - 8011:80
    networks:
      - tuandev_laravel
    restart: always

  blog_composer:
    image: blog
    volumes:
      - .:/app
    command: composer install
    networks:
      - tuandev_laravel

networks:
  tuandev_laravel:
    external: true
